lint:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: test
  image:
    name: oven/bun:1
  cache:
    - key:
        files:
          - bun.lockb
      paths:
        - node_modules
  script:
    - bun install --frozen-lockfile
    - bun lint
