check:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: test
  image:
    name: node:22-alpine
  cache:
    - key:
        files:
          - pnpm-lock.yaml
      paths:
        - .pnpm-store
  variables:
    HUSKY: 0
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm lint
    - pnpm test
