workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test
  - build
  - deploy

variables:
  HUSKY: 0

default:
  image:
    name: node:22
  cache:
    - key:
        files:
          - pnpm-lock.yaml
      paths:
        - .pnpm-store
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store

check:
  stage: test
  script:
    - pnpm install
    - echo "${CI_COMMIT_MESSAGE}" | pnpm exec commitlint
    - pnpm run check
    - pnpm run test

build:
  stage: build
  script:
    - pnpm install
    - pnpm run build
  artifacts:
    paths:
      - dist
